SET IDENTITY_INSERT [user_role_map] ON;
INSERT INTO [user_role_map] ([id],[user_id],[role_id]) VALUES (1,1,1);
INSERT INTO [user_role_map] ([id],[user_id],[role_id]) VALUES (2,1,2);
INSERT INTO [user_role_map] ([id],[user_id],[role_id]) VALUES (3,1,3);
INSERT INTO [user_role_map] ([id],[user_id],[role_id]) VALUES (4,2,2);
INSERT INTO [user_role_map] ([id],[user_id],[role_id]) VALUES (5,3,2);
INSERT INTO [user_role_map] ([id],[user_id],[role_id]) VALUES (6,3,1);
INSERT INTO [user_role_map] ([id],[user_id],[role_id]) VALUES (7,4,2);
INSERT INTO [user_role_map] ([id],[user_id],[role_id]) VALUES (8,5,2);
SET IDENTITY_INSERT [user_role_map] OFF;
