SET IDENTITY_INSERT [bpu_alarm_msg] ON;
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (1,0,'UHT1报警008:M9反馈故障',1);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (2,1,'UHT1报警009:M10反馈故障',1);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (3,2,'UHT1报警010:M11反馈故障',1);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (4,3,'UHT1报警011:M12反馈故障',1);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (5,4,'UHT1报警012:M13反馈故障',1);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (6,5,'UHT1报警013:M14反馈故障',1);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (7,6,'UHT1报警014:M15反馈故障',1);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (8,7,'UHT1报警015:M16反馈故障',1);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (9,8,'UHT1报警000:M2反馈故障',1);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (10,9,'UHT1报警001:M3反馈故障',1);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (11,10,'UHT1报警002:M4反馈故障',1);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (12,11,'UHT1报警003:M5反馈故障',1);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (13,12,'UHT1报警004:M6反馈故障',1);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (14,13,'UHT1报警005:M6A反馈故障',1);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (15,14,'UHT1报警006:M7反馈故障',1);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (16,15,'UHT1报警007:M8反馈故障',1);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (17,0,'UHT1报警024:灌装机没有准备好',2);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (18,1,'UHT1报警025:气压低',2);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (19,2,'N/A',2);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (20,3,'UHT1报警026:产品流量低或高',2);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (21,4,'UHT1报警027:产品流量故障FSH02',2);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (22,5,'UHT1报警029:无菌罐没有准备好或者高液位',2);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (23,6,'UHT1报警030:蒸汽障温度低TSL46',2);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (24,7,'UHT1报警031:蒸汽障温度低TSL47',2);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (25,8,'UHT1报警016:预杀菌温度TSL71故障',2);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (26,9,'UHT1报警017:保持管温度TSL42温度低TSL42',2);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (27,10,'UHT1报警018:CIP温度TSL71故障',2);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (28,11,'UHT1报警019:超高温平衡缸低液位',2);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (29,12,'UHT1报警020:V81反馈故障',2);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (30,13,'UHT1报警021:V83反馈故障',2);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (31,14,'UHT1报警022:碱故障',2);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (32,15,'UHT1报警023:酸故障',2);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (33,0,'UHT1报警040:热水回路压力低',3);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (34,1,'UHT1报警041:反馈故障',3);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (35,2,'UHT1报警042:TT42损坏',3);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (36,3,'UHT1报警043:TT71损坏',3);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (37,4,'UHT1报警044:TT46损坏',3);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (38,5,'UHT1报警045:TT47损坏',3);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (39,6,'UHT1报警046:TT830损坏',3);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (40,7,'N/A',3);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (41,8,'UHT1报警032:蒸汽障温度低TSL830TSL830',3);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (42,9,'UHT1报警033:冷却水压力低PSL10',3);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (43,10,'UHT1报警034:电导率低',3);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (44,11,'UHT1报警035:无菌罐通讯故障',3);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (45,12,'UHT1报警036:源通信故障',3);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (46,13,'UHT1报警037:目的通讯故障',3);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (47,14,'UHT1报警038:蒸汽压力低',3);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (48,15,'UHT1报警039:脱气罐液位高或者低',3);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (49,0,'UHT1报警056:均质机曲轴箱油温故障',4);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (50,1,'UHT1报警057:均质机减速箱油温故障',4);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (51,2,'UHT1报警058:V71反馈故障',4);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (52,3,'N/A',4);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (53,4,'UHT1报警060:超高温急停',4);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (54,5,'UHT1报警061:蒸汽障TSL831温度低',4);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (55,6,'UHT1报警062:TT831损坏',4);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (56,7,'UHT1报警063:均质机温度高',4);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (57,8,'UHT1报警048:TC44/TC62',4);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (58,9,'UHT1报警047:TT44损坏',4);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (59,10,'UHT1报警070:均质机油位高',4);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (60,11,'UHT1报警071:均质机油位低',4);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (61,12,'UHT1报警052:均质机曲轴箱过滤器故障',4);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (62,13,'UHT1报警053:均质机减速箱过滤器故障',4);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (63,14,'UHT1报警054:均质机曲轴箱油压故障',4);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (64,15,'UHT1报警055:均质机减速箱油压故障',4);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (65,0,'UHT1报警072:预杀菌温度TSL504故障',5);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (66,1,'UHT1报警073:预杀菌温度TSL502故障',5);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (67,2,'UHT1报警074:保持管时间故障',5);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (68,3,'UHT1报警075:LSH504',5);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (69,4,'UHT1报警076:TT502损坏',5);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (70,5,'UHT1报警077:TT504损坏',5);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (71,6,'UHT1报警078:电导率高',5);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (72,7,'N/A',5);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (73,8,'UHT1报警064:PT100损坏',5);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (74,9,'UHT1报警065:压差PSL63故障',5);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (75,10,'UHT1报警066:压差PSL62故障PSL63',5);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (76,11,'UHT1报警067:压差PSL61故障PSL63',5);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (77,12,'UHT1报警068:无效配方',5);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (78,13,'UHT1报警069:均质机油温高',5);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (79,14,'N/A',5);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (80,15,'UHT1报警059:V84反馈故障',5);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (81,0,'UHT1报警088:更换软盘',6);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (82,1,'UHT1报警089:LT504损坏',6);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (83,2,'UHT1报警090:产品流量传感器故障',6);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (84,3,'UHT1报警091:热水压力高',6);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (85,4,'UHT1报警092:背压高PSH60',6);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (86,5,'UHT1报警093:保持管时间故障',6);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (87,6,'UHT1报警094:生产无使能',6);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (88,7,'UHT1报警095:水冲无使能',6);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (89,8,'UHT1报警080:生产停止',6);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (90,9,'UHT1报警081:通讯故障CIP站',6);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (91,10,'UHT1报警082:通讯故障CIP站',6);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (92,11,'UHT1报警083: 碱浓度过高',6);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (93,12,'UHT1报警084: 碱浓度过低',6);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (94,13,'UHT1报警085:酸浓度过高',6);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (95,14,'UHT1报警086:酸浓度过低',6);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (96,15,'UHT1报警087:压差故障PT64',6);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (97,0,'UHT1报警104:预杀菌温度故障TSL901',7);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (98,1,'UHT1报警105:预杀菌温度故障TSL902',7);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (99,2,'UHT1报警106:LSL66',7);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (100,3,'UHT1报警107:PSL847',7);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (101,4,'UHT1报警108:TT4损坏',7);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (102,5,'UHT1报警109:TT6损坏',7);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (103,6,'UHT1报警110:TT62损坏',7);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (104,7,'UHT1报警111:TT64损坏',7);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (105,8,'UHT1报警096:压差故障PT65',7);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (106,9,'UHT1报警097:酸碱罐低液位',7);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (107,10,'UHT1报警098:a电导率高',7);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (108,11,'UHT1报警099:注射慢',7);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (109,12,'UHT1报警100:添加快',7);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (110,13,'UHT1报警101:',7);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (111,14,'UHT1报警102:酸碱平衡缸排地错误',7);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (112,15,'UHT1报警103:酸碱平衡缸溢出',7);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (113,8,'UHT1报警113:PSL846',8);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (114,9,'UHT1报警114:LT10损坏',8);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (115,10,'UHT1报警142:均质压力异常',8);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (116,11,'N/A',8);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (117,12,'UHT1报警115:产品在设备内',8);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (118,8,'UHT1报警148:无菌罐蒸汽障故障',9);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (119,0,'无菌罐报警00：M1故障',10);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (120,1,'无菌罐报警00：M2故障',10);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (121,2,'无菌罐报警00：M3故障',10);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (122,3,'无菌罐报警03：M1方向故障',10);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (123,4,'无菌罐报警04：M1振动故障',10);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (124,5,'无菌罐报警05：电源故障',10);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (125,6,'无菌罐报警06：材料ID故障',10);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (126,7,'无菌罐报警07：急停',10);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (127,8,'无菌罐报警08：无电源',10);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (128,9,'无菌罐报警09：面板冷却器故障',10);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (129,10,'无菌罐报警10：气压故障',10);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (130,11,'无菌罐报警11：过滤器故障',10);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (131,12,'无菌罐报警12：液位高故障',10);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (132,13,'无菌罐报警13：液位低故障',10);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (133,14,'无菌罐报警14：空罐故障',10);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (134,15,'无菌罐报警15：压力故障',10);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (135,0,'无菌罐报警16：杀菌温度故障',11);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (136,1,'无菌罐报警17：CIP温度故障',11);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (137,2,'无菌罐报警18：CIP单元故障',11);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (138,3,'无菌罐报警19：CIP通讯故障',11);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (139,4,'无菌罐报警20：TT90 损坏',11);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (140,5,'无菌罐报警21：TT101 损坏',11);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (141,6,'无菌罐报警22：TT101D 损坏',11);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (142,7,'无菌罐报警23：TT201A 损坏',11);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (143,8,'无菌罐报警24：TT201D 损坏',11);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (144,9,'无菌罐报警25：TT110 损坏',11);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (145,10,'无菌罐报警26：TT120 损坏',11);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (146,11,'无菌罐报警27：TT130 损坏',11);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (147,12,'无菌罐报警28：TT140 损坏',11);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (148,13,'无菌罐报警29：TT150 损坏',11);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (149,14,'无菌罐报警30：TT160 损坏',11);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (150,15,'无菌罐报警31：TT260 损坏',11);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (151,0,'无菌罐报警32：TT280 损坏',12);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (152,1,'无菌罐报警33：TT263 损坏',12);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (153,2,'无菌罐报警34：TT265 损坏',12);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (154,3,'无菌罐报警35：TT170 损坏',12);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (155,4,'无菌罐报警36：TT180 损坏',12);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (156,5,'无菌罐报警37：TT190 损坏',12);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (157,6,'无菌罐报警38：TT100 损坏',12);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (158,7,'无菌罐报警39：TT630 损坏',12);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (159,8,'无菌罐报警40：TT90 故障',12);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (160,9,'无菌罐报警41：TT101 故障',12);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (161,10,'无菌罐报警42：TT101D 故障',12);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (162,11,'无菌罐报警43：TT201A 故障',12);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (163,12,'无菌罐报警44：TT201D 故障',12);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (164,13,'无菌罐报警45：TT110 故障',12);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (165,14,'无菌罐报警46：TT120 故障',12);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (166,15,'无菌罐报警47：TT130 故障',12);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (167,0,'无菌罐报警48：TT140 故障',13);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (168,1,'无菌罐报警49：TT150 故障',13);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (169,2,'无菌罐报警50：TT160 故障',13);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (170,3,'无菌罐报警51：TT260 故障',13);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (171,4,'无菌罐报警52：TT280 故障',13);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (172,5,'无菌罐报警53：TT263 故障',13);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (173,6,'无菌罐报警54：TT265 故障',13);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (174,7,'无菌罐报警55：TT170 故障',13);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (175,8,'无菌罐报警56：TT180 故障',13);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (176,9,'无菌罐报警57：TT190 故障',13);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (177,10,'无菌罐报警58：TT100 故障',13);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (178,11,'无菌罐报警59：TT630 故障',13);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (179,12,'无菌罐报警60：V101 故障',13);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (180,13,'无菌罐报警60：V101 故障',13);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (181,14,'无菌罐报警61：V101L 故障',13);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (182,15,'无菌罐报警63：TT145 故障',13);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (183,0,'无菌罐报警64：V201 故障',14);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (184,1,'无菌罐报警65：V107 故障',14);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (185,2,'无菌罐报警66：V207 故障',14);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (186,3,'无菌罐报警67：',14);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (187,4,'无菌罐报警68：压力高故障',14);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (188,5,'无菌罐报警69：电池故障',14);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (189,6,'N/A',14);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (190,7,'N/A',14);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (191,8,'无菌罐报警72：V100 故障',14);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (192,9,'无菌罐报警73：V102 故障',14);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (193,10,'无菌罐报警74：V100 清洗反冲故障',14);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (194,11,'无菌罐报警75：源1通讯故障',14);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (195,12,'无菌罐报警76：源2通讯故障',14);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (196,13,'无菌罐报警77：目的通讯故障',14);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (197,14,'N/A',14);
INSERT INTO [bpu_alarm_msg] ([id],[alarm_msg_bit],[alarm_msg_info],[bpu_alarm_tag]) VALUES (198,15,'N/A',14);
SET IDENTITY_INSERT [bpu_alarm_msg] OFF;
