package com.tetrapak.metaclass;

public class Number {
    public static final int NUMBER_0 = 0;
    public static final int NUMBER_1 = 1;
    public static final int NUMBER_2 = 2;
    public static final int NUMBER_3 = 3;
    public static final int NUMBER_4 = 4;
    public static final int NUMBER_5 = 5;
    public static final int NUMBER_6 = 6;
    public static final int NUMBER_7 = 7;
    public static final int NUMBER_8 = 8;
    public static final int NUMBER_9 = 9;
    public static final int NUMBER_10 = 10;
    public static final int NUMBER_11 = 11;
    public static final int NUMBER_12 = 12;
    public static final int NUMBER_13 = 13;
    public static final int NUMBER_14 = 14;
    public static final int NUMBER_15 = 15;
    public static final int NUMBER_16 = 16;
    public static final int NUMBER_17 = 17;
    public static final int NUMBER_18 = 18;
    public static final int NUMBER_19 = 19;
    public static final int NUMBER_20 = 20;
    public static final int NUMBER_21 = 21;
    public static final int NUMBER_22 = 22;
    public static final int NUMBER_23 = 23;
    public static final int NUMBER_24 = 24;
    public static final int NUMBER_25 = 25;
    public static final int NUMBER_26 = 26;
    public static final int NUMBER_27 = 27;
    public static final int NUMBER_28 = 28;
    public static final int NUMBER_29 = 29;
    public static final int NUMBER_30 = 30;
    public static final int NUMBER_31 = 31;
    public static final int NUMBER_32 = 32;
    public static final int NUMBER_33 = 33;
    public static final int NUMBER_34 = 34;
    public static final int NUMBER_35 = 35;
    public static final int NUMBER_36 = 36;
    public static final int NUMBER_37 = 37;
    public static final int NUMBER_38 = 38;
    public static final int NUMBER_39 = 39;
    public static final int NUMBER_40 = 40;
    public static final int NUMBER_41 = 41;
}
