truncate table bpu_alarm_report_analyse_point;
SET IDENTITY_INSERT [bpu_alarm_report_analyse_point] ON;
INSERT INTO [bpu_alarm_report_analyse_point] ([id],[bpu_alarm_latest_analyse_date_time],[bpu_alarm_tag]) VALUES (1,'2013/7/16 0:00',1);
INSERT INTO [bpu_alarm_report_analyse_point] ([id],[bpu_alarm_latest_analyse_date_time],[bpu_alarm_tag]) VALUES (2,'2013/7/16 0:00',2);
INSERT INTO [bpu_alarm_report_analyse_point] ([id],[bpu_alarm_latest_analyse_date_time],[bpu_alarm_tag]) VALUES (3,'2013/7/16 0:00',3);
INSERT INTO [bpu_alarm_report_analyse_point] ([id],[bpu_alarm_latest_analyse_date_time],[bpu_alarm_tag]) VALUES (4,'2013/7/16 0:00',4);
INSERT INTO [bpu_alarm_report_analyse_point] ([id],[bpu_alarm_latest_analyse_date_time],[bpu_alarm_tag]) VALUES (5,'2013/7/16 0:00',5);
INSERT INTO [bpu_alarm_report_analyse_point] ([id],[bpu_alarm_latest_analyse_date_time],[bpu_alarm_tag]) VALUES (6,'2013/7/16 0:00',6);
INSERT INTO [bpu_alarm_report_analyse_point] ([id],[bpu_alarm_latest_analyse_date_time],[bpu_alarm_tag]) VALUES (7,'2013/7/16 0:00',7);
INSERT INTO [bpu_alarm_report_analyse_point] ([id],[bpu_alarm_latest_analyse_date_time],[bpu_alarm_tag]) VALUES (8,'2013/7/16 0:00',8);
INSERT INTO [bpu_alarm_report_analyse_point] ([id],[bpu_alarm_latest_analyse_date_time],[bpu_alarm_tag]) VALUES (9,'2013/7/16 0:00',9);
INSERT INTO [bpu_alarm_report_analyse_point] ([id],[bpu_alarm_latest_analyse_date_time],[bpu_alarm_tag]) VALUES (10,'2013/7/16 0:00',10);
INSERT INTO [bpu_alarm_report_analyse_point] ([id],[bpu_alarm_latest_analyse_date_time],[bpu_alarm_tag]) VALUES (11,'2013/7/16 0:00',11);
INSERT INTO [bpu_alarm_report_analyse_point] ([id],[bpu_alarm_latest_analyse_date_time],[bpu_alarm_tag]) VALUES (12,'2013/7/16 0:00',12);
INSERT INTO [bpu_alarm_report_analyse_point] ([id],[bpu_alarm_latest_analyse_date_time],[bpu_alarm_tag]) VALUES (13,'2013/7/16 0:00',13);
INSERT INTO [bpu_alarm_report_analyse_point] ([id],[bpu_alarm_latest_analyse_date_time],[bpu_alarm_tag]) VALUES (14,'2013/7/16 0:00',14);
SET IDENTITY_INSERT [bpu_alarm_report_analyse_point] OFF;
